on: [push]

jobs:
  salus_scan_job:
    runs-on: ubuntu-latest
    name: Federacy Salus Security Scan Example
    steps:
    - uses: actions/checkout@v1
    - name: Federacy Salus Security Scan
      id: salus_scan 
      uses: federacy/scan-action@0.1.1
